### ISSUE TITLE
npm run dev 之后好像date-fns失败

### ISSUE THREAD

**Issue by qq295823929** [07akioni/naive-ui-nuxt-demo#2]
![image](https://user-images.githubusercontent.com/38320579/172103700-731cc7a7-1fe5-4a20-8cc9-9da0f2423eb2.png)
如图,然后在首页的功能都不能正常使用

**Comment by 07akioni** [comment]
我人麻了，date-fns 这个包一堆问题

**Comment by 07akioni** [comment]
你先锁一下 2.29.0。

这个问题我晚上处理一下，发一版

**Comment by 07akioni** [comment]
demo 已经更新了，你可以拉一下，最新版也没问题
