### ISSUE TITLE
How to handle Tailwind's Preflight Style Override

### ISSUE THREAD

**Issue by OrbisK** [07akioni/naive-ui-nuxt-demo#3]
I am Not sure how to handle the Tailwind's Preflight Style Override.

I've tried:

```typescript
// plgins/some-plugin.ts
import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin((nuxtApp) => {
    if (process.client) {
        const meta = document.createElement('meta')
        meta.name = 'naive-ui-style'
        document.head.appendChild(meta)
    }
});
```

Reproduction: https://github.com/random-rip/primebot-frontend

**Comment by 07akioni** [comment]
Is this a CSR only app?

If it's an SSR app. Naive's style is inserted in HTML. So it's client side's responsibility to insert style in correct position.

**Comment by 07akioni** [comment]
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/18677354/177048686-ec568774-bd03-4db0-83e2-48ef669ea02d.png">

As you can see, naive's style is generated in server side so runtime inserted meta won't have effect. Also, tailwind preflight style is inserted in client side.

So the only way to solve your problem it to replace server generated style tag correctly in client side. I think you may write some code to replace them.
