### ISSUE TITLE
太慢了

### ISSUE THREAD

**Issue by CV-souryu** [07akioni/naive-ui-nuxt-demo#6]
nuxt dev 需要 20秒以上
CPU:i5-9400f 
RAM:16GB
https://github.com/Genshin-Impact-Cult-of-Noelle/Noelle-Nuxt3-SLS/tree/UISLOW

**Comment by 07akioni** [comment]
话说有试过别的项目吗？我觉得 nuxt 本身也不太快

**Comment by 07akioni** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/18677354/184934407-0974539a-1aff-4b77-bf8e-db13a9fb206c.png">

把这个加上，会快很多，和这个库 config 一致

**Comment by 07akioni** [comment]
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/18677354/184934513-20364651-7d6a-4842-aa01-80743730ee2e.png">

**Comment by 07akioni** [comment]
之前的问题是那个项目 naive-ui 没有放进 optimize deps，导致每次开启要发 2000 多个请求
