### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] CSSRender is not a function

### ISSUE THREAD

**Issue by SnowGuest** [07akioni/naive-ui-nuxt-demo#7]
In the latest Nuxt3 RC.8, the plugins of nuxt.config.ts and plugins are configured. After building, using pm2 to deploy the project, the following error will occur when accessing the specified domain name

![image](https://user-images.githubusercontent.com/59474029/184659365-f9037ba2-d3e9-4d42-a6a8-c133b4d3a3fb.png)

**Comment by 07akioni** [comment]
I think this is a nuxt issue. However we will fix it in next version.

**Comment by abhay-agarwal** [comment]
+1, same error using yarn. Doesn't happen on rc6

**Comment by 07akioni** [comment]
fixed
